name: Build image and release version

on:
  push:
    branches:
      - main

env:
  registry: ghcr.io
  image_name: ${{ github.repository }}
  argo_version_file: meldingstjenestefrontend-version

jobs:
  build:
    name: Docker build and push
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    outputs:
      image_url: ${{ steps.setOutput.outputs.image_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 20.x
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"

      - name: Run npm install and build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed
        run: |
          npm ci
          npm run build
      - name: Login to Github Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        with:
          github_token: ${{ github.token }}

      - name: Build Docker and push
        id: build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          push: true
          tags: ${{ env.registry }}/${{ github.repository }}:${{ steps.tag_version.outputs.new_tag }},${{ env.registry }}/${{ github.repository }}:latest

      - name: Set output with build values
        id: setOutput
        run: |
          echo "image_url=${{ env.registry }}/${{ github.repository }}@${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT
  pharos:
    name: Run Pharos with Required Permissions
    needs: build
    permissions:
      actions: read
      packages: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: "Run Pharos"
        uses: kartverket/pharos@fda2f571fa7d1df3e976e83ab54f3a3592991ded # v0.5.0
        with:
          image_url: ${{ needs.build.outputs.image_url }}

  argo:
    name: Update version in apps-repo
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Fetch token
        uses: octo-sts/action@a26b0c6455c7f13316f29a8766287f939e75f6c8 # v1.0.2
        id: octo-sts
        with:
          scope: kartverket/egenreg-apps
          identity: meldingstjeneste-frontend
      - name: Checkout apps-repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: kartverket/egenreg-apps
          ref: main
          token: ${{ steps.octo-sts.outputs.token }}
      - name: Update version
        run: |
          echo "\"${{ needs.build.outputs.image_url }}\"" > "env/atgcp1-dev/egenreg-main/${{ env.argo_version_file }}"
          git config --global user.email "noreply@kartverket.no"
          git config --global user.name "Egenreg CI"
          git commit -am "Update Egenreg ${{ env.argo_version_file }}"
          git push
